### ISSUE TITLE
Type error, followed by memory-fault-error in SBCL 

### ISSUE THREAD

**Issue by Inaimathi** [fukamachi/woo#14] opened 2015-02-12 02:32 UTC
#### Steps to reproduce:

     CL-USER> (ql:quickload :woo)
     To load "woo":
       Load 1 ASDF system:
         woo
     ; Loading "woo"
     
     (:WOO)
     CL-USER> 
     (woo:run
       (lambda (env)
         (declare (ignore env))
         '(200 (:content-type "text/plain") ("Hello, World"))))

In a browser, navigate to `localhost:5000`.

#### Expected:

See a plain text

     Hello, World

page in browser

#### Observed:

      <ERROR> [21:05:14] woo - The value 2779321106 is not of type (UNSIGNED-BYTE 8).

appears in REPL. The browser shows a loading icon and never displays content. If the stop button is clicked in browser, the REPL produces the following error 

     Unhandled memory fault at #x7FFF28004E60.
        [Condition of type SB-SYS:MEMORY-FAULT-ERROR]
     
     Restarts:
      0: [RETRY] Retry SLIME REPL evaluation request.
      1: [*ABORT] Return to SLIME's top level.
      2: [ABORT] Abort thread (#<THREAD "repl-thread" RUNNING {10048D8083}>)
     
     Backtrace:
       0: (SB-SYS:MEMORY-FAULT-ERROR)
       1: ("foreign function: call_into_lisp")
       2: ("foreign function: post_signal_tramp")
       3: ("foreign function: #x20220F8764")
       4: (WOO.EV.SOCKET:CLOSE-SOCKET #S(WOO.EV.SOCKET:SOCKET :WATCHERS #(#.(SB-SYS:INT-SAP #X7FFFE8005300) #.(SB-SYS:INT-SAP #X7FFFE8005340) #.(SB-SYS:INT-SAP #X7FFFE8005380)) :LAST-ACTIVITY 1.423707477550414d..
       5: (WOO.EV.TCP::TCP-READ-CB #<unavailable argument> #.(SB-SYS:INT-SAP #X7FFFE8005300) #<unavailable argument>)
       6: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/home/inaimathi/.cache/common-lisp/sbcl-1.1.15.debian-linux-x64/home/inaimathi/quicklisp/dists/quicklisp/software/woo-20150113-..
       7: ("foreign function: call_into_lisp")
       8: ("foreign function: funcall3")
       9: ("foreign function: #x20101085")
      10: ("foreign function: #x2014A118DE")
      11: (WOO:RUN #<FUNCTION (LAMBDA (ENV)) {100EFC697B}> :DEBUG T :PORT 5000 :ADDRESS "0.0.0.0" :BACKLOG NIL :FD NIL :WORKER-NUM NIL)
      12: (SB-INT:SIMPLE-EVAL-IN-LEXENV (WOO:RUN (LAMBDA (ENV) (DECLARE (IGNORE ENV)) (QUOTE (200 (:CONTENT-TYPE "text/plain") ("Hello, World"))))) #<NULL-LEXENV>)
      13: (EVAL (WOO:RUN (LAMBDA (ENV) (DECLARE (IGNORE ENV)) (QUOTE (200 (:CONTENT-TYPE "text/plain") ("Hello, World"))))))
      14: (SWANK::EVAL-REGION " ..)
      15: ((LAMBDA NIL :IN SWANK-REPL::REPL-EVAL))
      16: (SWANK-REPL::TRACK-PACKAGE #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {100EFA414B}>)
      17: (SWANK::CALL-WITH-RETRY-RESTART "Retry SLIME REPL evaluation request." #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {100EFA408B}>)
      18: (SWANK::CALL-WITH-BUFFER-SYNTAX NIL #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {100EFA406B}>)
      19: (SWANK-REPL::REPL-EVAL " ..)
      20: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SWANK-REPL:LISTENER-EVAL " ..)
      21: (EVAL (SWANK-REPL:LISTENER-EVAL " ..)
      22: (SWANK:EVAL-FOR-EMACS (SWANK-REPL:LISTENER-EVAL " ..)
      23: (SWANK::PROCESS-REQUESTS NIL)
      24: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
      25: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
      26: (SWANK/SBCL::CALL-WITH-BREAK-HOOK #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SWANK::HANDLE-REQUESTS) {10048E00EB}>)
      27: ((FLET SWANK/BACKEND:CALL-WITH-DEBUGGER-HOOK :IN "/home/inaimathi/quicklisp/dists/quicklisp/software/slime-2.12/swank/sbcl.lisp") #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SWANK:..
      28: (SWANK::CALL-WITH-BINDINGS ((*STANDARD-OUTPUT* . #1=#<SWANK/GRAY::SLIME-OUTPUT-STREAM {10048B9653}>) (*STANDARD-INPUT* . #2=#<SWANK/GRAY::SLIME-INPUT-STREAM {1002B00183}>) (*TRACE-OUTPUT* . #1#) (*ERR..
      29: (SWANK::HANDLE-REQUESTS #<SWANK::MULTITHREADED-CONNECTION {1003A42AF3}> NIL)
      30: ((FLET #:WITHOUT-INTERRUPTS-BODY-1117 :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
      31: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
      32: ((FLET #:WITHOUT-INTERRUPTS-BODY-537 :IN SB-THREAD::CALL-WITH-MUTEX))
      33: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7FFFF488EC6B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THR..
      34: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "repl-thread" RUNNING {10048D8083}> #S(SB-THREAD:SEMAPHORE :NAME "Thread setup semaphore" :%COUNT 0 :WAITCOUNT 0 :MUTEX #<SB-THREAD:MU..
      35: ("foreign function: call_into_lisp")
      36: ("foreign function: new_thread_trampoline")

#### Build Info:

This is `woo-20150113-git` installed using `quicklisp`, running on 64-bit Debian. Observed in `SBCL 1.1.15.debian` and `SBCL 1.2.8.nixos`. The Debian version is using libev directly out of the Jesse repos (so [looks like `1:4.15-3`](https://packages.debian.org/search?keywords=libev)), while the `nix` version is running `libev-4.15` and `libevdev-1.3.1`.

**Comment by fukamachi** [comment] 2015-02-12 06:45
I couldn't reproduce the error on both of Mac and Linux Mint.
Can you please try it with the latest Woo (at a272ee44a79bd20d1319d16ccf2cc04e1ca42a73) and give me the stacktraces?

**Comment by Inaimathi** [comment] 2015-02-12 13:43
Doesn't look like the same error, but sure:

     Callback Error: the message-complete callback failed
       The value 2779321106 is not of type (UNSIGNED-BYTE 8).
        [Condition of type FAST-HTTP.ERROR:CB-MESSAGE-COMPLETE]
     
     Restarts:
      0: [RETRY] Retry SLIME REPL evaluation request.
      1: [*ABORT] Return to SLIME's top level.
      2: [ABORT] Abort thread (#<THREAD "repl-thread" RUNNING {10048D8083}>)
     
     Backtrace:
       0: (WOO.EV.SOCKET:WRITE-SOCKET-BYTE #<unavailable argument> #<unavailable argument>) [tl,external]
       1: (WOO.RESPONSE:RESPONSE-HEADERS-BYTES #<unavailable argument> #<unavailable argument> #<unavailable argument> #<unavailable argument>)
       2: (WOO::HANDLE-NORMAL-RESPONSE #<unavailable argument> #<unavailable argument> #<unavailable argument>)
       3: (WOO::HANDLE-RESPONSE #S(FAST-HTTP.HTTP:HTTP-REQUEST :METHOD :GET :MAJOR-VERSION 1 :MINOR-VERSION 1 :STATUS 0 :CONTENT-LENGTH NIL :CHUNKED-P NIL :UPGRADE-P NIL :HEADERS #<HASH-TABLE :TEST EQUAL :COUNT..
       4: ((LAMBDA (FAST-HTTP.HTTP:HTTP) :IN FAST-HTTP:MAKE-PARSER) #<unavailable argument>)
       5: (FAST-HTTP.PARSER::PARSE-BODY #<unavailable argument> #<unavailable argument> #<unavailable argument> #<unavailable argument> #<unavailable argument> #<unavailable argument>)
       6: (FAST-HTTP.PARSER:PARSE-REQUEST #<unavailable argument> #<unavailable argument> #<unavailable argument> :START #<unavailable argument> :END #<unavailable argument>)
       7: ((LAMBDA (FAST-HTTP::DATA &KEY (FAST-HTTP::START 0) FAST-HTTP::END) :IN FAST-HTTP:MAKE-PARSER) #<unavailable argument> :START #<unavailable argument> :END #<unavailable argument>)
       8: (WOO::READ-CB #S(WOO.EV.SOCKET:SOCKET :WATCHERS #(#.(SB-SYS:INT-SAP #X7FFFE8012E60) #.(SB-SYS:INT-SAP #X7FFFE8012EA0) #.(SB-SYS:INT-SAP #X7FFFE8012EE0)) :LAST-ACTIVITY 1.4237494112551289d9 :FD 8 :REMO..
       9: (WOO.EV.TCP::TCP-READ-CB #<unavailable argument> #.(SB-SYS:INT-SAP #X7FFFE8012E60) #<unavailable argument>)
      10: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/home/inaimathi/.cache/common-lisp/sbcl-1.1.15.debian-linux-x64/home/inaimathi/quicklisp/local-projects/woo/src/ev/socket.fasl"..
      11: ("foreign function: call_into_lisp")
      12: ("foreign function: funcall3")
      13: ("foreign function: #x20101085")
      14: ("foreign function: #x2009838E1E")
      15: (WOO:RUN #<FUNCTION (LAMBDA (ENV)) {1004E68D6B}> :DEBUG T :PORT 5000 :ADDRESS "0.0.0.0" :BACKLOG NIL :FD NIL :WORKER-NUM NIL)
      16: (SB-INT:SIMPLE-EVAL-IN-LEXENV (WOO:RUN (LAMBDA (ENV) (DECLARE (IGNORE ENV)) (QUOTE (200 (:CONTENT-TYPE "text/plain") ("Hello, World"))))) #<NULL-LEXENV>)
      17: (EVAL (WOO:RUN (LAMBDA (ENV) (DECLARE (IGNORE ENV)) (QUOTE (200 (:CONTENT-TYPE "text/plain") ("Hello, World"))))))
      18: (SWANK::EVAL-REGION "(woo:run ..)
      19: ((LAMBDA NIL :IN SWANK-REPL::REPL-EVAL))
      20: (SWANK-REPL::TRACK-PACKAGE #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {1004DA951B}>)
      21: (SWANK::CALL-WITH-RETRY-RESTART "Retry SLIME REPL evaluation request." #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {1004DA945B}>)
      22: (SWANK::CALL-WITH-BUFFER-SYNTAX NIL #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {1004DA943B}>)
      23: (SWANK-REPL::REPL-EVAL "(woo:run ..)
      24: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SWANK-REPL:LISTENER-EVAL "(woo:run ..)
      25: (EVAL (SWANK-REPL:LISTENER-EVAL "(woo:run ..)
      26: (SWANK:EVAL-FOR-EMACS (SWANK-REPL:LISTENER-EVAL "(woo:run ..)
      27: (SWANK::PROCESS-REQUESTS NIL)
      28: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
      29: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
      30: (SWANK/SBCL::CALL-WITH-BREAK-HOOK #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SWANK::HANDLE-REQUESTS) {10048E00EB}>)
      31: ((FLET SWANK/BACKEND:CALL-WITH-DEBUGGER-HOOK :IN "/home/inaimathi/quicklisp/dists/quicklisp/software/slime-2.12/swank/sbcl.lisp") #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SWANK:..
      32: (SWANK::CALL-WITH-BINDINGS ((*STANDARD-OUTPUT* . #1=#<SWANK/GRAY::SLIME-OUTPUT-STREAM {10048B9653}>) (*STANDARD-INPUT* . #2=#<SWANK/GRAY::SLIME-INPUT-STREAM {10032B8003}>) (*TRACE-OUTPUT* . #1#) (*ERR..
      33: (SWANK::HANDLE-REQUESTS #<SWANK::MULTITHREADED-CONNECTION {1003A42AF3}> NIL)
      34: ((FLET #:WITHOUT-INTERRUPTS-BODY-1117 :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
      35: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
      36: ((FLET #:WITHOUT-INTERRUPTS-BODY-537 :IN SB-THREAD::CALL-WITH-MUTEX))
      37: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7FFFF488EC6B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THR..
      38: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "repl-thread" RUNNING {10048D8083}> #S(SB-THREAD:SEMAPHORE :NAME "Thread setup semaphore" :%COUNT 0 :WAITCOUNT 0 :MUTEX #<SB-THREAD:MU..
      39: ("foreign function: call_into_lisp")
      40: ("foreign function: new_thread_trampoline")

**Comment by fukamachi** [comment] 2015-02-12 15:12
Thanks.

It sounds like an environment dependant problem.
Could you give me the result from `(woo.response::current-rfc-1123-timestamp)` and `local-time:*default-timezone*`?

**Comment by Inaimathi** [comment] 2015-02-12 16:13
CL-USER> (woo.response::current-rfc-1123-timestamp)
     "Thu, 12 Feb 2015 11:11:10 +600"
     CL-USER> local-time:*default-timezone*
     #<LOCAL-TIME::TIMEZONE EDT EST EWT EPT>
     CL-USER> 

and that paste is actually missing some bytes that show up in REPL. Manual transcription follows.

     CL-USER> (woo.response::current-rfc-1123-timestamp)
     "Thu, 12 Feb 2015 11:11:10 +\372\221\214\222600"

**Comment by fukamachi** [comment] 2015-02-12 16:26
Okay, I got it.

It must be a problem during sending a `Date` header with some timezones.
It should be fixed soon.

Meanwhile, you can avoid the problem by setting `local-time:*default-timezone*` to `local-time:+utc-zone+`.

For the record, here's the reproducible code:

```common-lisp
(let ((local-time:*default-timezone* (local-time::%make-simple-timezone "edt" "EDT" -6)))
  (woo.response::current-rfc-1123-timestamp))
```

**Comment by Inaimathi** [comment] 2015-02-12 19:50
Confirming that the following works fine:

    (let ((local-time:*default-timezone*  local-time:+utc-zone+))
      (woo:run
       (lambda (env)
         (declare (ignore env))
         '(200 (:content-type "text/plain") ("Hello, World")))))

**Closed** 2015-02-13 01:06 UTC

**Comment by fukamachi** [comment] 2015-02-13 01:07
Fixed in the above commit.
Thank you for reporting! I really didn't aware the timezone problem.

**Comment by Inaimathi** [comment] 2015-02-13 19:41
Confirmed fixed. Thanks for the quick response (I'll note more if I see them).
